refactor: remove old plugfest test suite
w3c-ccg/vc-http-api pull request #162
Opened 2021-03-10 22:05 UTC by tplooker

Removes the old plugfest based test suite.

2021-03-10 22:07 UTC, OR13 approved these changes

2021-03-11 09:02 UTC, peacekeeper requested changes
Why? We can add a comment that it has been superceded by the new one and shouldn't be used anymore, but I think it's worth preserving it in the repo so we have a record of it.

2021-03-11 19:08 UTC, tplooker commented
@peacekeeper it will be preserved in history I just personally find it confusing to keep around a deprecated test suite in the repo.

2021-03-12 21:10 UTC, fqutishat approved these changes

2021-03-18 19:33 UTC, OR13 commented
@tplooker can you add a link to the old plugfest to the readme, so its not confusing.

2021-03-21 17:58 UTC, OR13 commented
IMO this is blocked by providing a link to the old suite in the readme... this kind of house cleaning is 100% necessary to ensure a positive first time contributor experience. its very bad form to keep dead / stale code around in the main branch.

2021-03-22 19:18 UTC, tplooker commented
Ping @peacekeeper @msporny do you guys have any opinions on this?

2021-03-23 11:41 UTC, peacekeeper commented
Okay let's include a link to the old suite in the README and then remove the old code, as suggested by @OR13 .

@tplooker do you want to add a commit to this PR to add such a link to README?

2021-03-24 03:19 UTC, tplooker commented
@OR13 and @peacekeeper added a link to the old test suite.

2021-03-24 09:59 UTC, peacekeeper approved these changes

2021-03-24 20:32 UTC, TallTed commented on packages/vc-http-api-test-server/README.md
> +This test suite supersedes the original which is available [here](https://github.com/w3c-ccg/vc-http-api/tree/b4df10dfdce98b453a2333e7ec1728a10bcc54d1/packages/plugfest-2020)
```suggestion
This test suite is meant to replace the original, which remains available 
[here](https://github.com/w3c-ccg/vc-http-api/tree/b4df10dfdce98b453a2333e7ec1728a10bcc54d1/packages/plugfest-2020) 
for reference purposes.
```

2021-03-26 18:35 UTC, merged