Increase test timeout to one minute
w3c-ccg/vc-http-api pull request #177
Opened 2021-04-01 15:35 UTC by clehner

Close #173

2021-04-01 15:46 UTC, msporny approved these changes

2021-04-01 15:46 UTC, msporny commented on packages/vc-http-api-test-server/services/jest/cli.js
> +const JEST_TEST_TIMEOUT_MS = 60 * 1000;
Gotta give enough time for the hamsters to bring the wheels up to speed.

2021-04-01 18:00 UTC, OR13 requested changes
this is not a good idea... we can't keep bumping the timeout to make up for the fact that we are testing dids that are slow, in a test suite about VCs.

All credentials issued by DIDs other than DID Key should be removed.

2021-04-15 17:04 UTC, peacekeeper approved these changes
I think this makes sense, since this is for testing VCs, not DIDs. If someone has super slow DIDs but still produces valid VCs, then the tests should pass.

> All credentials issued by DIDs other than DID Key should be removed.

I don't think it's fair to limit the test suite to only a single DID method (`did:key`), since not everyone may support that. I do think however that the reporting can be improved to count each test only once. I.e. if you configure 10 different issuer DIDs, the reporting should show the same number of tests as if you configure 1 issuer DID.

2021-05-11 14:05 UTC, merged