Support JWT
w3c-ccg/vc-http-api pull request #208
Opened 2021-06-25 16:30 UTC by clehner

Add support for [JWT](https://www.w3.org/TR/vc-data-model/#json-web-token) [proof format](https://www.w3.org/TR/vc-data-model/#proof-formats) in the API.

The `VerifiableCredential` and `VerifiablePresentation` types are changed to allow a `string` value, using `oneOf`.

An option for issuing or presenting a credential is added, `proofFormat`, with possible values "jwt" or "ldp". Would there be more idiomatic existing terms to use here?

This API change assumes that the existing routes and options handling LDPs can be used with JWTs. Should it be documented how that should work? e.g. the `domain` option could correspond to the `aud` claim.

Should there be an issue/present option for "additional JWT claims" that the caller may want to add outside the VC/VP?

Related issues: #42, #207

2021-06-25 16:45 UTC, msporny commented
I expect this to be an unpopular opinion... but with the new work on BBS+, the lack of interoperable examples of JWT VCs, and a lack of examples of interoperable tests for JWT VCs... I'm concerned about the work this might create for the VC HTTP API group.

> An option for issuing or presenting a credential is added, proofFormat, with possible values "jwt" or "ldp". Would there be more idiomatic existing terms to use here?

How many implementers are going to support the JWT format? Are there implementers that would like to never support the JWT format, if possible? Are there other proofFormats in the works? Can we just express the proofFormat via the `type`?

> This API change assumes that the existing routes and options handling LDPs can be used with JWTs. Should it be documented how that should work? e.g. the domain option could correspond to the aud claim.

Feels like adding a lot of work to the group at this stage... especially given that none of the implementers to date have requested that the API support these features, and especially since the JsonWebSiganture2020 suite exists: https://w3c-ccg.github.io/lds-jws2020/

> Should there be an issue/present option for "additional JWT claims" that the caller may want to add outside the VC/VP?

Again, feels like scope creep.

I'd prefer that those wanting JWT support write the VC JWT test suite first (or demonstrate interop of some kind before requiring this API to support it).

2021-06-26 12:12 UTC, David-Chadwick commented
JWT interworking may be relatively easy to achieve. The VCs that we create can be validated by the jwt.io debugger, which supports a much larger audience than just the W3C VC implementors. Currently our VP syntax can be validated but not the signature as the jwt.io debugger does not support DIDs.
So I would be happy to start to perform interworking tests with other JWT implementors if they ping me.

2021-06-28 13:22 UTC, OR13 commented
We have some library support for JWT baseed VCs and JWS generally (since they are a building block for many popular VC proofs like `Ed25519Signature2018` and `EcdsaSecp256k1Siganture2019`.

I feel a bit torn on this issue.

## Arguments for Supporting JWT

- VC-JWT is described in the spec
- JOSE / JWA tooling is more widely available and understood, since its older
- Without better interoperability tests, its easier for big guys like Microsoft to ignore the W3C VC Data Model and call whatever JWT thing they make a VC, and there is no proof that its not interoperable.

## Arguments against Supporting JWT

- VC-JWT doesn't add a lot to vanilla JOSE
- VC-JWT failed to ensure interoperability by allowing lots of optional fields
- VC-JWT date format includes milliseconds and is literally incompatible with W3C / XSD Date time.
- VC-JWT never defined  a resolution or dereferencing for key material or proof purposes so we would be guessing about how that maps to DIDs (though I suspect  over time there may now we rough consensus to do the thing that aligns with LD proofs)
- VC-JWT does not support bls12381 / bbs or Schnorr for secp256k1, and we need to update the registry to do so... 
- `vp` and `vc` are STILL not registered: https://w3c.github.io/vc-data-model/#iana-considerations, https://www.iana.org/assignments/jose/jose.xhtml

## Conclusion

Of all these issues, the most frustrating for me is the registration stuff.  JOSE / JWT are undeniably easier to implement, and understand... yet innovation with JWT is controlled by registry updates... At the same time, many JWT implementers have been actively hostile to the major improvement that VCs have over JWTs, which is semantics for the claims... This has led me to generally dislike JWT implementations, but I have to admit, that my views of JWT have been distorted by the implementers and at its core, I still think VC-JWT has a place in the world, especially with better guidance on required vs optional fields. 

Unfortunately, I don't know that there is consensus on that part, for example, in our implementations we don't verify VC-JWTs that fail to define their claims in their context... yet this (verifying the credential semantics) is not a requirement of the spec, yet `@context` is... and... 

https://spec.smarthealth.cards/credential-modeling/#mapping-into-the-w3c-vc-data-model

```
"@context": [
  "https://www.w3.org/2018/credentials/v1",
  {
    "@vocab": "https://smarthealth.cards#",
    "fhirBundle": {
      "@id": "https://smarthealth.cards#fhirBundle",
      "@type": "@json"
    }
  }
]
```

Telling people to add a normatively required field:

https://w3c.github.io/vc-data-model/#contexts

> Verifiable credentials and verifiable presentations MUST include a @context property.

I would 100% support VC-JWT, if we don't loose any semantic checks, but this kind of "squint at a normal JWT and call it a VC / VP"... is incredibly harmful and undermines everything we are working for here, w.r.t. interoperability and standards compliance.

I'm not sure other VC-JWT implementers would agree with me, and frankly, the spec should have solved for this issue...

So in the interest of making it possible to support VC-JWT, can we agree to the following:

1. "Verifiable credentials and verifiable presentations MUST include a @context property."
2. vc['@context'] MUST be signed over when constructing the payload for the JWS that is produced for a VC-JWT
3. vp['@context'] MUST be signed over when constructing the payload for the JWS that is produced for a VP-JWT

2021-06-28 13:25 UTC, OR13 requested changes
There is a lack of consensus regarding VC-JWT normative requirements, we've observed significantly different / non interoperable formats in the wild.

I am not against supporting VC-JWT, but we will need to get clearer consensus on what that means (especially w.r.t. issues like signatures and verification), before we can commit to api / spec text on this subject.

In the interest of making this "change request" actionable, perhaps we can get the VC-JWT data model and signature / verification requirements documented explicitly so we can point to that when we say "we support VC-JWT".

2021-06-28 13:32 UTC, Sakurann commented
@OR13 vc vp are registered in JWT registry: https://www.iana.org/assignments/jwt/jwt.xhtml

> vp and vc are STILL not registered: https://w3c.github.io/vc-data-model/#iana-considerations, https://www.iana.org/assignments/jose/jose.xhtml

2021-06-28 13:34 UTC, OR13 commented
@Sakurann Thanks! I was searching the wrong place.

2021-06-28 13:35 UTC, Sakurann commented
@OR13 what do you mean by
> VC-JWT failed to ensure interoperability by allowing lots of optional fields

`@context` is being included in VC-JWT too

2021-06-28 13:46 UTC, David-Chadwick commented
@OR13 VC-JWT failed to ensure interoperability by allowing lots of optional fields

Sorry I dont understand this comment. VCs have an infinite number of optional fields, so JWTs are inheriting this from VCs.

2021-06-28 13:48 UTC, David-Chadwick commented
> There is a lack of consensus regarding VC-JWT normative requirements, we've observed significantly different / non interoperable formats in the wild.
> 
The best way to address this is by the VC WG clarifying any ambiguities or omissions in the V2 Recommendation that is now being worked on.

2021-06-28 13:52 UTC, David-Chadwick commented
@OR13 yet innovation with JWT is controlled by registry updates..

This restriction has now been removed by adding the vc and vp data types to the IANA registry. This means that any new properties in VCs or VPs are automatically encapsulated in the vc and vp claims and therefore do not need to be registered in IANA. The normal @context registration procedure is used.

2021-06-28 14:09 UTC, OR13 commented
@David-Chadwick I mean the registries control `alg` such as ES256, ES256K, etc...

@Sakurann and @David-Chadwick "the normal `@context` process is being used".... how?

certainly its not being following by Microsoft and Apple in SmartHealthCards....

injecting payload attributes would break the signature... signing over the payload without the context is not normatively compliant.

2021-06-28 14:35 UTC, peacekeeper commented
I am generally in favor of this. In the very first version of the API (=long obsolete), there were options to specify the credential format as well as proof format (the limitation to JSON-LD only happened later):

https://github.com/w3c-ccg/vc-http-api/blob/main/docs/versions/v0.0.0/vc-http-api.yml#L481

But I also understand concerns of others in this thread about added complexity. If this addition creates problems for implementers, maybe better to first discuss on a call.

2021-06-28 14:58 UTC, David-Chadwick commented
@OR13 certainly its not being following by Microsoft and Apple in SmartHealthCards..

whenever did Microsoft conform to standards? They have always twisted them in some way: Kerberos, LDAP, email and now VCs. This does not surprise me at all.

2021-06-28 15:00 UTC, clehner commented
> Are there other proofFormats in the works?

In the `proofFormat` option in `v0.0.0` which @peacekeeper pointed out, there was a third possible value, "blockcerts". But I don't know the status of that format. I would be interested to know why those options were removed (and `credentialFormatOptions` and ` proofFormatOptions`) - I'm unable to find discussion of it.

@David-Chadwick in #209 has mentioned OIDC's encapsulation format; I don't know if that would be considered a proof format for VC Data Model.

VC Data Model lists just the two [proof formats](https://www.w3.org/TR/vc-data-model/#proof-formats); it also references [VC Extension Registry](https://w3c-ccg.github.io/vc-extension-registry/), but does not explicitly mention proof formats as an extension point.

> Can we just express the proofFormat via the type?

I think that could work. A proof type(s) could be defined for use here - like the "synthetic" `JwtProof2020` in DIF's [did-jwt-vc](https://github.com/decentralized-identity/did-jwt-vc/) implementation - that could define mapping between JWT and VP/VC with Proof object, building on what is already in VC Data Model v1.0. An exception would be if a proof type supported both JWT format and LDP-only format, a format option might be needed to request one or the other.

In the interest of simplicity, I amend the commit to remove `proofFormat`. Since VC JWTs using JWS don't have a proof type property, to enable verification according to specific JWT-supporting proof type, I add "type" to VerifyOptions (similar to #197).

2021-06-28 15:01 UTC, David-Chadwick commented
@OR13 wrt to @context, I can only speak for our own implementation. We add @contexts to our VCs for the subject properties being defined by our issuers. So as far as I know our VCs are 100% compliant.

2021-06-28 15:17 UTC, David-Chadwick commented
@clehner "I don't know if that would be considered a proof format for VC Data Model."

No, the OIDC encapsulation is there to tell the relying party whether the returned VP is a JWT or LDProof'ed VP. That's all. You can see the JSON here
https://bitbucket.org/openid/connect/src/master/openid-connect-4-verifiable-presentations/openid-connect-4-verifiable-presentations-1_0.md

2021-06-28 15:26 UTC, David-Chadwick commented
@msporny We support any version that complies with the standard. Full stop.
And we clarify in v2 of the standard any ambiguities that still exist for people (Personally, because I helped write the Recommendation I did not find any of the current text confusing. But then I might have had implicit knowledge that others are missing and that needs to be documented)

2021-06-28 17:40 UTC, Sakurann commented
Microsoft's Verifiable Credentials Service adds @context to the VCs - you can check it if you try sample issuer/verifier in https://docs.microsoft.com/en-us/azure/active-directory/verifiable-credentials/get-started-verifiable-credentials

For Smart Health Cards, there is a mapping at
https://spec.smarthealth.cards/credential-modeling/#mapping-into-the-w3c-vc-data-model

2021-06-28 18:24 UTC, TallTed commented
@Sakurann -- Please codefence (by wrapping in backticks, either single or triple) any `@`entity you put in github markdown, e.g.,``` `@context` ```.  Otherwise, they get pinged about many discussions which are of no interest to them.  (It's worth editing [your recent comment](https://github.com/w3c-ccg/vc-http-api/pull/208#issuecomment-869881849).)

2021-06-28 18:38 UTC, OR13 commented
@Sakurann 

> For Smart Health Cards, there is a mapping at
https://spec.smarthealth.cards/credential-modeling/#mapping-into-the-w3c-vc-data-model

This proves that smart health cards are not VC Data Model conformant... you don't need a mapping when you follow the normative requirements in a standard.

> Microsoft's Verifiable Credentials Service adds @context to the VCs - you can check it if you try sample issuer/verifier in https://docs.microsoft.com/en-us/azure/active-directory/verifiable-credentials/get-started-verifiable-credentials

I cannot confirm the behavior from the link, can you link directly to a VC-JWT in either compact or decoded form?

2021-06-28 22:30 UTC, OR13 commented
Here are the test vectors we use for our VC-JWT implementation:

https://github.com/transmute-industries/vc.js/tree/master/packages/vc.js/src/__fixtures__/test-vectors/vc-jwt

2021-06-29 17:04 UTC, clehner commented
@OR13

> In the interest of making this "change request" actionable, perhaps we can get the VC-JWT data model and signature / verification requirements documented explicitly so we can point to that when we say "we support VC-JWT".

Where might be a good place for this?

2021-06-29 18:15 UTC, msporny commented
> Where might be a good place for this?

Set up a `vc-jwt-test-suite` repository as a CCG work item, fill it with vc-jwt tests, and get multiple organizations to support passing all of the tests.

2021-06-29 18:57 UTC, David-Chadwick commented
@msporny "ideally, this would just be a vc-signatures-test-suite which would cover LD Signatures as well"
Ideally it would NOT include LD Signatures as well, but would use standard JWT defined algorithms and signature procedures. JWT does not need canonicalisation for example. JWT does however support X.509 PKCs, another well used standard.

2021-06-29 22:02 UTC, OR13 commented
I am in favor of closing this PR, when:

There exists a w3c ccg work item titled: `vc-jwt-test-suite`.

Until then , the PR should remain up, to gather feedback / comments.

@clehner would you mind making the proposal and linking it back here?

2021-07-01 00:31 UTC, clehner commented
@OR13 @msporny I can do that. I'll need a couple days to prepare.

2021-07-05 13:02 UTC, bumblefudge commented
Update: the C&C meeting (and tomorrow's CCG meeting as well) are intended as requirements-gathering and input-gathering sessions to help scope and inform the test suite work item. Both sessions are public and people with relevant experience to share and compare are invited to make either or both, observing the IPR policies of the respective venues.

2021-07-16 14:35 UTC, clehner commented
Work item proposal for JWT interop testing is opened at https://github.com/w3c-ccg/community/issues/198

2021-07-18 17:59 UTC, msporny commented
> Work item proposal for JWT interop testing is opened at [w3c-ccg/community#198](https://github.com/w3c-ccg/community/issues/198)

Given that we now have this work item proposal, can we close this PR?

2021-07-19 13:25 UTC, clehner commented
@msporny yes, closing.

2021-07-19 13:25 UTC, closed without merging

2023-04-22 03:25 UTC, sloops77 commented
@msporny @clehner 
I'm Andres Olave from the Velocity Network. After our call a few weeks ago, I am exploring adding support for VC-API for some use cases for the Velocity Network. However, we will only be able to have the network ecosystsem support the vc-jwt's in the short to medium term as we do not want to burden them with two credential formats. Is this something that can be revisited since https://github.com/w3c-ccg/community/issues/198 is closed

2023-04-22 14:48 UTC, msporny commented
@sloops77 wrote:
> I have been exploring adding support for VC-API for some use cases for the Velocity Network. However, we will only be able to have the network ecosystem support vc-jwt's (for the short to medium term) as we do not want to burden members with two credential formats. Is this something that can be revisited since [w3c-ccg/community#198](https://github.com/w3c-ccg/community/issues/198) is closed

The VC API is capable of supporting an arbitrary number of credential formats, so yes, we've just been waiting for someone that's interested in actually implementing this feature. The easiest place to start would be with these two endpoints:

`[/credentials/issue](https://w3c-ccg.github.io/vc-api/#issue-credential)` and `[/credentials/verify](https://w3c-ccg.github.io/vc-api/#verify-credential)`

The presumption is that the endpoint for `/credentials/issue` would be configured to issue VC-JWTs (you'd give it the same parameters, but the result would be a VC-JWT held in a field called `vcJwt`, and the endpoint for verifying would take a parameter called `vcJwt`. 

I'll note that if you go this route, it'll be highly experimental as everyone else that has demonstrated interop in JFF Plugfest #3 (17+ platforms) using the VC API has taken the `application/vc+ld+json` route with Data Integrity Proofs. There are people out there issuing VC-JWTs, but due to how the VC-JWT spec is changing, and how implementations have taken different paths there, demonstrating interop will be more difficult until there is better tooling/testing available.

In any case, if you are committed to doing VC-JWT (which I suggest you avoid until things settle down a bit more there), then I'd start with the above.