Add introduction to authorization section.
w3c-ccg/vc-http-api pull request #228
Opened 2021-09-11 23:55 UTC by msporny

This PR is a partial alternate to PR #226. This particular PR is a non-normative introductory section to the Authorization section in the specification. It sets expectations, but delegates the normative language to subsections (in separate PRs). It differs from PR #226 in a few ways:

* It is only the introduction, the specific normative sections on authz mechanisms will be in separate PRs.
* It does not say anything about RAR (separate PR).
* It does not say anything about OAuth2.0 (separate PR).
* It does not say anything about Delegation (separate PR).
* It does not say anything about GNAP (separate PR).
* It does not say anything about forbidden methods (separate PR).

2021-09-13 14:00 UTC, OR13 approved these changes

2021-09-13 16:05 UTC, mprorock approved these changes

2021-09-13 16:17 UTC, mkhraisha approved these changes

2021-09-21 03:59 UTC, peacekeeper approved these changes
I have been mostly quiet on the recent authorization discussions, but since I'm listed as one of the code owners in this repo, and I'm also an implementer, I'll write a few lines here.

I sympathize quite a bit with Adrian's comments in the last few weeks/months. What I have heard in the various calls and threads is that "the vendors want to do X", but "what's good for the individual is Y". I admit I don't know the details of the different proposals well enough to understand the implications (e.g. OAuth2 = digital slavery? GNAP/RAR = sovereignty?), but I do think Adrian's point is valid that we shouldn't just necessarily do what's easiest for vendors. Reminds me of the did:web discussion, which is great for vendors but doesn't really offer individidual sovereignty.

As a vendor implementing this VC HTTP API, we (Danube Tech) haven't implemented any authorization mechanism. So far we have considered this to not be part of the API but to happen elsewhere, e.g. in external API gateways, proxies, firewall rules, authenticated TLS connections, etc. I think that other implementers have thought about this more thoroughly than we have, therefore I haven't been too involved in the discussions about specific technology choices.

As a code owner, I think Manu has done a nice job with this and the subsequent PRs to break up individual topics into more manageable pieces, so I suggest we use this as a basis.

2021-09-21 20:45 UTC, jandrieu commented on index.html
> +A conforming <dfn>VC HTTP API client</dfn> is ...
```suggestion
A conforming <dfn>VC API client</dfn> is ...
```

2021-09-21 20:45 UTC, jandrieu commented on index.html
> +A conforming <dfn>VC HTTP API server</dfn> is ...
```suggestion
A conforming <dfn>VC API server</dfn> is ...
```

2021-09-21 20:45 UTC, jandrieu commented on index.html
> +The VC HTTP API can be deployed in a variety of networking environments which
```suggestion
The VC API can be deployed in a variety of networking environments which
```

2021-09-21 20:46 UTC, jandrieu commented on index.html
> +require conforming <a>VC HTTP API clients</a> to utilize secure authorization
```suggestion
require conforming <a>VC API clients</a> to utilize secure authorization
```

2021-09-21 20:49 UTC, OR13 requested changes
I require @jandrieu 's proposed changes to be accepted to approve.

2021-09-21 20:51 UTC, jandrieu requested changes
Just the name thing.

2021-09-25 23:23 UTC, msporny commented
All change requests merged, no objections, merging.

2021-09-25 23:24 UTC, merged